"""Historical backtest engine for v2-preview AI analysis."""

from __future__ import annotations

import csv
import json
import math
from dataclasses import asdict, is_dataclass
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path
from typing import Any, Optional

from ..common import HUNDRED, ZERO, pct_change, quantize, safe_div
from ..contracts.input_contract import ContextBundle, OHLCVBar, OHLCVSeries
from ..hypothesis.hypothesis_registry import HypothesisRegistry
from ..orchestration import AIAnalysisResultBuilder
from .data_loader import load_symbol_series
from .models import (
    BacktestConfig,
    BacktestResult,
    BacktestSummary,
    DailySignal,
    HypothesisBacktestRow,
    Trade,
)
from .xlsx_writer import write_xlsx


def run_backtest(config: BacktestConfig, *, write_files: bool = True) -> BacktestResult:
    """Run a no-lookahead daily backtest over one or more Taiwan symbols."""

    all_bars = {
        symbol: load_symbol_series(
            symbol,
            start=config.start,
            end=config.end,
            warmup_bars=config.warmup_bars,
            data_dir=config.data_dir,
            allow_mock=config.allow_mock,
        )
        for symbol in config.symbols
    }

    trades: list[Trade] = []
    signals: list[DailySignal] = []
    hypothesis_events: list[dict[str, Any]] = []
    for symbol, series in all_bars.items():
        symbol_trades, symbol_signals, symbol_hypothesis_events = _run_symbol_backtest(symbol, series, config)
        trades.extend(symbol_trades)
        signals.extend(symbol_signals)
        hypothesis_events.extend(symbol_hypothesis_events)

    equity_curve = _build_equity_curve(config, all_bars, trades)
    summary = _build_summary(config, trades, equity_curve)
    hypothesis_rows = _build_hypothesis_rows(hypothesis_events, trades)

    result = BacktestResult(
        config=config,
        summary=summary,
        trades=sorted(trades, key=lambda trade: (trade.entry_date, trade.symbol)),
        daily_signals=sorted(signals, key=lambda item: (item.signal_date, item.symbol)),
        hypothesis_rows=hypothesis_rows,
        equity_curve=equity_curve,
    )
    if write_files:
        generated = write_backtest_outputs(result)
        result = BacktestResult(
            config=result.config,
            summary=result.summary,
            trades=result.trades,
            daily_signals=result.daily_signals,
            hypothesis_rows=result.hypothesis_rows,
            equity_curve=result.equity_curve,
            generated_files=generated,
        )
    return result


def write_backtest_outputs(result: BacktestResult) -> dict[str, Path]:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    symbols = "_".join(result.config.symbols[:4])
    run_dir = result.config.output_dir / f"{timestamp}_{result.config.strategy}_{symbols}"
    run_dir.mkdir(parents=True, exist_ok=True)

    sheets = {
        "Summary": [_flatten(result.summary)],
        "Trades": [_flatten(item) for item in result.trades],
        "DailySignals": [_flatten(item) for item in result.daily_signals],
        "Hypotheses": [_flatten(item) for item in result.hypothesis_rows],
        "EquityCurve": [_flatten(item) for item in result.equity_curve],
        "Config": [_flatten(result.config)],
        "Readme": [{
            "note": "This workbook is generated by backend.technical_analyzer.v1.backtest.runner.",
            "entry_model": "Signals are produced using data through signal_date; entries use next trading day's open.",
            "strict_mode": "Set --require-rr-pass to enforce the v2 3:1 RR gate.",
        }],
    }

    for name, rows in sheets.items():
        _write_csv(run_dir / f"{name}.csv", rows)

    summary_path = run_dir / "summary.json"
    summary_path.write_text(
        json.dumps(_jsonable({
            "summary": result.summary,
            "config": result.config,
            "generated_at": datetime.now().isoformat(),
        }), ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    xlsx_path = run_dir / "backtest_results.xlsx"
    write_xlsx(xlsx_path, sheets)
    return {
        "run_dir": run_dir,
        "xlsx": xlsx_path,
        "summary_json": summary_path,
    }


def _run_symbol_backtest(
    symbol: str,
    series: OHLCVSeries,
    config: BacktestConfig,
) -> tuple[list[Trade], list[DailySignal], list[dict[str, Any]]]:
    builder = AIAnalysisResultBuilder()
    bars = series.bars
    trades: list[Trade] = []
    signals: list[DailySignal] = []
    hypothesis_events: list[dict[str, Any]] = []
    open_position: dict[str, Any] | None = None
    trade_counter = 0

    start_index = max(config.warmup_bars, 1)
    for index in range(start_index, len(bars) - 1):
        bar = bars[index]
        if bar.date < config.start or bar.date > config.end:
            continue

        window = OHLCVSeries(symbol, bars[: index + 1])
        result = builder.build(symbol, window, ContextBundle(market_cap_bucket="large"))
        v2 = result.v2_quant_analysis
        risk_plan = v2.risk_execution

        if open_position is not None:
            maybe_trade = _maybe_exit_position(open_position, bars, index, config, result)
            if maybe_trade is not None:
                trades.append(maybe_trade)
                open_position = None

        reject_reason = _entry_reject_reason(result, config)
        entry_candidate = reject_reason is None and open_position is None
        signals.append(_daily_signal(symbol, bar, result, entry_candidate, reject_reason))
        hypothesis_events.extend(_hypothesis_events(symbol, bars, index, result, config.forward_days))

        if entry_candidate:
            entry_bar = bars[index + 1]
            trade_counter += 1
            position_pct = _position_pct(risk_plan.kelly_fraction, config)
            entry_price = _apply_slippage(entry_bar.open, config.slippage_bps, "buy")
            capital = config.initial_capital * position_pct
            shares = capital / entry_price if entry_price > ZERO else ZERO
            open_position = {
                "trade_id": f"{symbol}-{trade_counter:04d}",
                "symbol": symbol,
                "signal_date": bar.date,
                "entry_date": entry_bar.date,
                "entry_price": entry_price,
                "shares": shares,
                "position_pct": position_pct,
                "signal": result.overall_scores.signal,
                "confidence": result.overall_scores.confidence,
                "risk": result.overall_scores.risk,
                "rr_ratio": risk_plan.rr_ratio,
                "rr_pass": risk_plan.rr_pass,
                "stop_loss": risk_plan.stop_loss_price,
                "take_profit": risk_plan.take_profit_price,
                "two_b_status": v2.two_b_reversal.status,
                "poc_price": v2.volume_profile.poc_price,
                "hypothesis_ids": v2.hypothesis_ids,
            }

    if open_position is not None:
        last_index = len(bars) - 1
        final_trade = _close_position(open_position, bars[last_index].date, bars[last_index].close, "end_of_data", config)
        trades.append(final_trade)

    return trades, signals, hypothesis_events


def _entry_reject_reason(result, config: BacktestConfig) -> Optional[str]:
    v2 = result.v2_quant_analysis
    if result.overall_scores.signal < config.min_signal:
        return "signal_below_min"
    if result.overall_scores.confidence < config.min_confidence:
        return "confidence_below_min"
    if result.overall_scores.risk > config.max_risk:
        return "risk_above_max"
    if config.require_rr_pass and not v2.risk_execution.rr_pass:
        return "rr_below_3_to_1"
    if v2.fundamental_gate.status == "fail":
        return "fundamental_gate_fail"
    if v2.fundamental_gate.status == "unknown" and not config.allow_fundamental_unknown:
        return "fundamental_gate_unknown"
    if v2.risk_execution.forced_exit:
        return "forced_exit_active"
    return None


def _maybe_exit_position(
    position: dict[str, Any],
    bars: list[OHLCVBar],
    index: int,
    config: BacktestConfig,
    result,
) -> Trade | None:
    bar = bars[index]
    if bar.date < position["entry_date"]:
        return None

    stop_loss = position.get("stop_loss")
    take_profit = position.get("take_profit")
    if stop_loss is not None and bar.low <= stop_loss:
        return _close_position(position, bar.date, _apply_slippage(stop_loss, config.slippage_bps, "sell"), "stop_loss", config)
    if take_profit is not None and bar.high >= take_profit:
        return _close_position(position, bar.date, _apply_slippage(take_profit, config.slippage_bps, "sell"), "take_profit", config)

    holding_days = (bar.date - position["entry_date"]).days
    if holding_days >= config.max_holding_days:
        return _close_position(position, bar.date, _apply_slippage(bar.close, config.slippage_bps, "sell"), "max_holding_days", config)
    if result.v2_quant_analysis.risk_execution.forced_exit:
        next_bar = bars[index + 1] if index + 1 < len(bars) else bar
        exit_price = next_bar.open if next_bar is not bar else bar.close
        return _close_position(position, next_bar.date, _apply_slippage(exit_price, config.slippage_bps, "sell"), result.v2_quant_analysis.risk_execution.forced_exit_reason or "forced_exit", config)
    return None


def _close_position(position: dict[str, Any], exit_date: date, exit_price: Decimal, reason: str, config: BacktestConfig) -> Trade:
    entry_price = position["entry_price"]
    shares = position["shares"]
    gross_pnl = (exit_price - entry_price) * shares
    buy_value = entry_price * shares
    sell_value = exit_price * shares
    fees = (buy_value + sell_value) * config.fee_rate
    tax = sell_value * config.tax_rate
    net_pnl = gross_pnl - fees - tax
    gross_return = pct_change(exit_price, entry_price, ZERO) or ZERO
    net_return = safe_div(net_pnl, buy_value, ZERO) or ZERO
    return Trade(
        trade_id=position["trade_id"],
        symbol=position["symbol"],
        signal_date=position["signal_date"],
        entry_date=position["entry_date"],
        entry_price=quantize(entry_price, "0.01"),
        exit_date=exit_date,
        exit_price=quantize(exit_price, "0.01"),
        exit_reason=reason,
        shares=quantize(shares, "0.0001"),
        position_pct=position["position_pct"],
        gross_return_pct=quantize(gross_return, "0.01"),
        net_return_pct=quantize(net_return * HUNDRED, "0.01"),
        gross_pnl=quantize(gross_pnl, "0.01"),
        fees=quantize(fees, "0.01"),
        tax=quantize(tax, "0.01"),
        net_pnl=quantize(net_pnl, "0.01"),
        holding_days=max((exit_date - position["entry_date"]).days, 0),
        signal=position["signal"],
        confidence=position["confidence"],
        risk=position["risk"],
        rr_ratio=position["rr_ratio"],
        rr_pass=position["rr_pass"],
        stop_loss=position["stop_loss"],
        take_profit=position["take_profit"],
        two_b_status=position["two_b_status"],
        poc_price=position["poc_price"],
        hypothesis_ids=list(position["hypothesis_ids"]),
    )


def _daily_signal(symbol: str, bar: OHLCVBar, result, entry_candidate: bool, reject_reason: Optional[str]) -> DailySignal:
    v2 = result.v2_quant_analysis
    return DailySignal(
        symbol=symbol,
        signal_date=bar.date,
        close=bar.close,
        signal=result.overall_scores.signal,
        confidence=result.overall_scores.confidence,
        risk=result.overall_scores.risk,
        direction=result.overall_direction.value,
        fundamental_gate=v2.fundamental_gate.status,
        rr_ratio=v2.risk_execution.rr_ratio,
        rr_pass=v2.risk_execution.rr_pass,
        kelly_fraction=v2.risk_execution.kelly_fraction,
        poc_price=v2.volume_profile.poc_price,
        poc_breakdown=v2.volume_profile.poc_breakdown_flag,
        two_b_status=v2.two_b_reversal.status,
        two_b_confirmed=v2.two_b_reversal.confirmed,
        ma20_p_crit=v2.time_boxes.get("ma20").p_crit if v2.time_boxes.get("ma20") else None,
        ma60_p_crit=v2.time_boxes.get("ma60").p_crit if v2.time_boxes.get("ma60") else None,
        forced_exit=v2.risk_execution.forced_exit,
        forced_exit_reason=v2.risk_execution.forced_exit_reason,
        entry_candidate=entry_candidate,
        reject_reason=reject_reason,
        data_quality=result.data_quality,
    )


def _hypothesis_events(symbol: str, bars: list[OHLCVBar], index: int, result, forward_days: int) -> list[dict[str, Any]]:
    future_index = min(index + forward_days, len(bars) - 1)
    if future_index <= index:
        return []
    current = bars[index]
    future = bars[future_index]
    forward_return = pct_change(future.close, current.close, ZERO) or ZERO
    v2 = result.v2_quant_analysis
    events: list[dict[str, Any]] = []

    def add(hypothesis_id: str, active: bool, bullish: bool = True) -> None:
        if not active:
            return
        hit = forward_return > ZERO if bullish else forward_return < ZERO
        events.append({
            "symbol": symbol,
            "date": current.date,
            "hypothesis_id": hypothesis_id,
            "forward_return_pct": quantize(forward_return, "0.01"),
            "hit": hit,
        })

    add("V2001", v2.fundamental_gate.status == "pass", True)
    add("V2002", v2.fundamental_gate.status == "pass", True)
    add("V2003", v2.fundamental_gate.status == "pass", True)
    add("V2004", any(box.ma_acceleration_flag for box in v2.time_boxes.values()), True)
    add("V2005", v2.volume_profile.poc_breakdown_flag, False)
    add("V2006", v2.two_b_reversal.confirmed, True)
    add("V2007", v2.risk_execution.rr_pass, True)
    add("V2008", v2.risk_execution.kelly_fraction > ZERO, True)
    return events


def _build_equity_curve(config: BacktestConfig, all_bars: dict[str, OHLCVSeries], trades: list[Trade]) -> list[dict[str, Any]]:
    dates = sorted({
        bar.date
        for series in all_bars.values()
        for bar in series.bars
        if config.start <= bar.date <= config.end
    })
    close_maps = {
        symbol: {bar.date: bar.close for bar in series.bars}
        for symbol, series in all_bars.items()
    }
    last_close: dict[str, Decimal] = {}
    curve: list[dict[str, Any]] = []
    for day in dates:
        realized = sum((trade.net_pnl for trade in trades if trade.exit_date <= day), ZERO)
        unrealized = ZERO
        open_count = 0
        for trade in trades:
            if trade.entry_date <= day < trade.exit_date:
                close = close_maps.get(trade.symbol, {}).get(day)
                if close is not None:
                    last_close[trade.symbol] = close
                close = last_close.get(trade.symbol)
                if close is not None:
                    unrealized += (close - trade.entry_price) * trade.shares
                    open_count += 1
        equity = config.initial_capital + realized + unrealized
        curve.append({
            "date": day,
            "equity": quantize(equity, "0.01"),
            "realized_pnl": quantize(realized, "0.01"),
            "unrealized_pnl": quantize(unrealized, "0.01"),
            "open_positions": open_count,
        })
    return curve


def _build_summary(config: BacktestConfig, trades: list[Trade], equity_curve: list[dict[str, Any]]) -> BacktestSummary:
    final_equity = equity_curve[-1]["equity"] if equity_curve else config.initial_capital
    total_return = pct_change(final_equity, config.initial_capital, ZERO) or ZERO
    wins = [trade for trade in trades if trade.net_pnl > ZERO]
    losses = [trade for trade in trades if trade.net_pnl <= ZERO]
    gross_profit = sum((trade.net_pnl for trade in wins), ZERO)
    gross_loss = abs(sum((trade.net_pnl for trade in losses if trade.net_pnl < ZERO), ZERO))
    returns = [trade.net_return_pct for trade in trades]
    win_rate = Decimal(len(wins)) / Decimal(len(trades)) * HUNDRED if trades else None
    avg_return = sum(returns, ZERO) / Decimal(len(returns)) if returns else None
    profit_factor = safe_div(gross_profit, gross_loss)
    avg_holding = sum((Decimal(trade.holding_days) for trade in trades), ZERO) / Decimal(len(trades)) if trades else None
    exposure = _exposure_pct(config, trades, equity_curve)
    sharpe = _sharpe(equity_curve)
    annualized = _annualized_return(config.initial_capital, final_equity, config.start, config.end)
    return BacktestSummary(
        strategy=config.strategy,
        start=config.start,
        end=config.end,
        symbols=config.symbols,
        initial_capital=config.initial_capital,
        final_equity=quantize(final_equity, "0.01"),
        total_return_pct=quantize(total_return, "0.01"),
        annualized_return_pct=quantize(annualized, "0.01") if annualized is not None else None,
        max_drawdown_pct=quantize(_max_drawdown(equity_curve), "0.01"),
        sharpe_ratio=quantize(sharpe, "0.01") if sharpe is not None else None,
        total_trades=len(trades),
        winning_trades=len(wins),
        losing_trades=len(losses),
        win_rate=quantize(win_rate, "0.01") if win_rate is not None else None,
        avg_trade_return_pct=quantize(avg_return, "0.01") if avg_return is not None else None,
        expectancy_pct=quantize(avg_return, "0.01") if avg_return is not None else None,
        profit_factor=quantize(profit_factor, "0.01") if profit_factor is not None else None,
        avg_holding_days=quantize(avg_holding, "0.01") if avg_holding is not None else None,
        exposure_pct=quantize(exposure, "0.01") if exposure is not None else None,
    )


def _build_hypothesis_rows(events: list[dict[str, Any]], trades: list[Trade]) -> list[HypothesisBacktestRow]:
    registry = HypothesisRegistry.load_default()
    rows: list[HypothesisBacktestRow] = []
    trade_by_hypothesis: dict[str, list[Trade]] = {}
    for trade in trades:
        for hypothesis_id in trade.hypothesis_ids:
            trade_by_hypothesis.setdefault(hypothesis_id, []).append(trade)
    for entry in sorted(registry.entries.values(), key=lambda item: item.hypothesis_id):
        if entry.module != "V2":
            continue
        hypothesis_events = [event for event in events if event["hypothesis_id"] == entry.hypothesis_id]
        trade_samples = trade_by_hypothesis.get(entry.hypothesis_id, [])
        event_count = len(hypothesis_events)
        hit_count = sum(1 for event in hypothesis_events if event["hit"])
        hit_rate = Decimal(hit_count) / Decimal(event_count) * HUNDRED if event_count else None
        avg_forward = (
            sum((event["forward_return_pct"] for event in hypothesis_events), ZERO) / Decimal(event_count)
            if event_count
            else None
        )
        avg_trade = (
            sum((trade.net_return_pct for trade in trade_samples), ZERO) / Decimal(len(trade_samples))
            if trade_samples
            else None
        )
        sample_type = "forward_return" if event_count else "trade_return" if trade_samples else "none"
        rows.append(HypothesisBacktestRow(
            hypothesis_id=entry.hypothesis_id,
            module=entry.module,
            topic=entry.topic,
            description=entry.description,
            event_count=event_count,
            hit_count=hit_count,
            hit_rate=quantize(hit_rate, "0.01") if hit_rate is not None else None,
            avg_forward_return_pct=quantize(avg_forward, "0.01") if avg_forward is not None else None,
            avg_trade_return_pct=quantize(avg_trade, "0.01") if avg_trade is not None else None,
            sample_type=sample_type,
        ))
    return rows


def _position_pct(kelly_fraction: Decimal, config: BacktestConfig) -> Decimal:
    if kelly_fraction > ZERO:
        return min(kelly_fraction, config.max_position_pct)
    return min(config.base_position_pct, config.max_position_pct)


def _apply_slippage(price: Decimal, bps: Decimal, side: str) -> Decimal:
    adjustment = bps / Decimal("10000")
    return price * (Decimal("1") + adjustment if side == "buy" else Decimal("1") - adjustment)


def _max_drawdown(equity_curve: list[dict[str, Any]]) -> Decimal:
    peak: Decimal | None = None
    max_dd = ZERO
    for row in equity_curve:
        equity = row["equity"]
        peak = equity if peak is None else max(peak, equity)
        drawdown = pct_change(equity, peak, ZERO) or ZERO
        max_dd = min(max_dd, drawdown)
    return abs(max_dd)


def _sharpe(equity_curve: list[dict[str, Any]]) -> Optional[Decimal]:
    if len(equity_curve) < 3:
        return None
    returns: list[float] = []
    for previous, current in zip(equity_curve, equity_curve[1:]):
        prev = Decimal(previous["equity"])
        curr = Decimal(current["equity"])
        daily = safe_div(curr - prev, prev)
        if daily is not None:
            returns.append(float(daily))
    if len(returns) < 2:
        return None
    avg = sum(returns) / len(returns)
    variance = sum((item - avg) ** 2 for item in returns) / (len(returns) - 1)
    std = math.sqrt(variance)
    if std == 0:
        return None
    return Decimal(str((avg / std) * math.sqrt(252)))


def _annualized_return(initial: Decimal, final: Decimal, start: date, end: date) -> Optional[Decimal]:
    days = max((end - start).days, 1)
    if initial <= ZERO or final <= ZERO:
        return None
    value = (float(final / initial) ** (365 / days) - 1) * 100
    return Decimal(str(value))


def _exposure_pct(config: BacktestConfig, trades: list[Trade], equity_curve: list[dict[str, Any]]) -> Optional[Decimal]:
    if not equity_curve:
        return None
    total_position_days = sum(Decimal(max((trade.exit_date - trade.entry_date).days, 1)) for trade in trades)
    denominator = Decimal(len(equity_curve) * max(len(config.symbols), 1))
    return total_position_days / denominator * HUNDRED


def _write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    headers: list[str] = []
    for row in rows:
        for key in row.keys():
            if key not in headers:
                headers.append(key)
    with path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=headers)
        writer.writeheader()
        for row in rows:
            writer.writerow({key: _csv_value(row.get(key)) for key in headers})


def _flatten(value: Any) -> dict[str, Any]:
    if is_dataclass(value):
        value = asdict(value)
    if not isinstance(value, dict):
        return {"value": value}
    return {key: _jsonable(item) for key, item in value.items()}


def _jsonable(value: Any) -> Any:
    if is_dataclass(value):
        return {key: _jsonable(item) for key, item in asdict(value).items()}
    if isinstance(value, Decimal):
        return float(value)
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, (date, datetime)):
        return value.isoformat()
    if isinstance(value, list):
        return [_jsonable(item) for item in value]
    if isinstance(value, tuple):
        return [_jsonable(item) for item in value]
    if isinstance(value, dict):
        return {str(key): _jsonable(item) for key, item in value.items()}
    return value


def _csv_value(value: Any) -> Any:
    if isinstance(value, (list, tuple, dict)):
        return json.dumps(_jsonable(value), ensure_ascii=False)
    if isinstance(value, Decimal):
        return str(value)
    if isinstance(value, (date, datetime)):
        return value.isoformat()
    return value
